<a href="https://colab.research.google.com/github/lephuocdat2000/Advanced-CV/blob/main/Dog-and-Cat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [80]:
from PIL import Image
import numpy as np
import zipfile
from io import StringIO
import imghdr
import cv2 
from sklearn.model_selection import train_test_split
from torchvision import models
import torch
from torchvision import transforms
import tensorflow as tf

In [81]:
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Resize(227)])

In [82]:
alexnet = models.alexnet(pretrained=True)
alexnet.classifier=alexnet.classifier[0:5]

#Đọc file data 

In [83]:
path_to_zip_file = '/content/drive/MyDrive/Thị giác máy tính/Thị giác máy tính nâng cao/Dog and Cat.zip'
imgzip = zipfile.ZipFile(path_to_zip_file)
inflist = imgzip.infolist()
images=[]
labels=[]
for f in inflist:
     if '.jpg' in f.filename:
       ifile = imgzip.open(f)
       img = Image.open(ifile)
       #Cho vào mạng alexnet
       img_t=transform(img)
       batch_t = torch.unsqueeze(img_t,0)
       out = alexnet(batch_t)
       out=out.detach().numpy()/255.0
      #  image_as_array = np.array(img, np.uint8)
      #  image_as_array = cv2.resize(image_as_array,(227,227))
       images.append(out)
       if 'dog' in f.filename: labels.append(1)
       elif 'cat' in f.filename: labels.append(0)

In [84]:
images=np.array(images)
labels=np.array(labels)

Load pre-train model

In [85]:
X_train, X_test, y_train, y_test = train_test_split(images,labels, test_size=0.2, random_state=42)

In [86]:
X_train=X_train.reshape(X_train.shape[0],X_train.shape[1]*X_train.shape[2])
X_test=X_test.reshape(X_test.shape[0],X_test.shape[1]*X_test.shape[2])

In [96]:
X_train

array([[ -3.6326578 ,   0.9012166 ,  -1.8559165 , ...,  -3.382327  ,
         -6.157464  ,  -3.5215354 ],
       [ -8.411607  ,  -7.082859  ,  -2.5301101 , ...,  -5.0959353 ,
         -2.3819644 ,  -1.6842092 ],
       [ -2.9649746 ,  -2.0328767 ,  -1.3086956 , ...,  -1.2761222 ,
         -5.6152897 ,   0.57499486],
       ...,
       [ -5.132268  ,  -3.1537852 ,  -3.1077569 , ...,  -2.4760664 ,
         -8.920271  ,  -3.4972641 ],
       [-28.108461  , -22.496906  ,  -5.283181  , ...,  -7.8922634 ,
        -17.40657   , -22.050331  ],
       [ -7.6477966 ,  -7.778644  ,  -1.1458132 , ...,  -5.719802  ,
        -13.386326  , -13.346991  ]], dtype=float32)

In [98]:
from sklearn.svm import SVC
model = SVC(gamma='auto')
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [99]:
y_pred=model.predict(X_test)

In [100]:
 from sklearn.metrics import accuracy_score
 accuracy_score(y_test, y_pred)

0.475

In [101]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0])

In [102]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])